### ISSUE TITLE
不支持52810了吗

### ISSUE THREAD

**Issue by jeromeli002** [genokolar/nrf52-keyboard#11]
最后打包的时候出错了
Merging file "nrf52_kbd_sign_with_sd.hex" into output.

Overlapping segments detected at address 102400.ERROR: The hex files cannot be merged since there are conflicts.

make: *** [../../application/main/project/app.mk:395：all] 错误 60

![1](https://user-images.githubusercontent.com/5648129/135982294-e7226c0a-77a2-4d8c-a3b4-91c78898475a.png)

**Comment by genokolar** [comment]
支持，你这是合并出错了。更新你的mergehex程序试试。
参考：
https://github.com/genokolar/nrf52_tools

**Comment by jeromeli002** [comment]
> 支持，你这是合并出错了。你的mergehex程序熟练。 参考：[https](https://github.com/genokolar/nrf52_tools) : [//github.com/genokolar/nrf52_tools](https://github.com/genokolar/nrf52_tools)

mergehex version: 10.14.0还是一样的错误

**Comment by genokolar** [comment]
看了下。是因为52810或52811的空间不足，加入bootloader的话会导致无法合成。解决办法二个：
1、不使用bootloader，使用make merge_softdevice  生成不带bootloader的包
2、使用bootloader，修改rules.mk，去掉一些模块，比如RGB 和COMMAND
