### ISSUE TITLE
OLED屏幕在无设备连接的情况下会常亮

### ISSUE THREAD

**Issue by KiraLJK** [genokolar/nrf52-keyboard#15]
当键盘没有连接到设备的时候，OLED屏幕过一小会会自动亮起并且保持常亮，试过亮了一个小时都不会灭。并且是卡住的状态，随便按一个按键它会刷新一下，比如电量显示会先变空再变回正常电量，然后继续保持常亮。但是如果用左右shift+P休眠后就不会继续亮起了。

**Comment by genokolar** [comment]
SDK15的已经不再更新
