### ISSUE TITLE
符号键怎么单独设置为一个按键

### ISSUE THREAD

**Issue by weekinro** [genokolar/nrf52-keyboard#20]
你好，我想只按一个键就出来一个符号（例如：按一个键输入~或者按一个键就输入!）这样怎么写KEYMAP
例如QMK中写KC_TILD表示~
或者怎么实现类似于QMK中的LSFT(KC_XXX)表示同时按SHIFT+XXX(键）

**Comment by genokolar** [comment]
参看高级按键
