### ISSUE TITLE
分支不支持RGB灯带了嘛？rgb灯带键没反应

### ISSUE THREAD

**Issue by jeromeli002** [genokolar/nrf52-keyboard#23]
分支不支持RGB灯带了嘛？值支持rgb矩阵了？
设置的rgb灯带键没反应，
自己编译的刷完亮红灯，设置rgb灯带键，都没反应
RGBLIGHT_ENABLE = yes     #启用RGB灯。这个不能用了？？？

**Comment by Lingyi0601** [comment]
键值设置错了，能亮就代表能用

**Comment by jeromeli002** [comment]
> 键值设置错了，能亮就代表能用

![image](https://user-images.githubusercontent.com/5648129/198423451-49dcbbc8-4cf0-4bce-9b44-f705c97f9d18.png)
设置的这些键完全没反应，能亮不代表就能用吧，灯带有时候信号线不接手碰一下也会亮，

**Comment by Lingyi0601** [comment]
灯带模式你还是自己在keymap里面写fn控制吧，灯带的改键工具改了也控制不了

**Comment by Lingyi0601** [comment]
> > 键值设置错了，能亮就代表能用
> 
> ![image](https://user-images.githubusercontent.com/5648129/198423451-49dcbbc8-4cf0-4bce-9b44-f705c97f9d18.png) 设置的这些键完全没反应，能亮不代表就能用吧，灯带有时候信号线不接手碰一下也会亮，

灯带模式你还是自己在keymap里面写fn控制吧，灯带的改键工具改了也控制不了

**Comment by jeromeli002** [comment]
> Reference in ne
这样啊…………
用jim的仓库没问题，试试葛老师分支结果不行了………………

**Comment by genokolar** [comment]
应该是支持的哦，刚测试了下，没有问题

**Comment by jeromeli002** [comment]
> 

组合键是可以切换的，就是配置工具里面的那几个灯键设置进去没反应

**Comment by genokolar** [comment]
OK了

> > 
> 
> 组合键是可以切换的，就是配置工具里面的那几个灯键设置进去没反应
