### ISSUE TITLE
多旋钮和radial没有开放的吗？

### ISSUE THREAD

**Issue by jeromeli002** [genokolar/nrf52-keyboard#25]
多旋钮和radial没有开放的吗？
看见新曾键盘HAL67 Rev.A支持多旋钮，
复制这个键盘来改加上RADIAL_CONTROLLER = yes编译出来旋钮完全不能用

**Comment by genokolar** [comment]
暂时没有上传代码

**Comment by genokolar** [comment]
多旋钮代码已上传

**Comment by jeromeli002** [comment]
能用那种中空旋钮吗，那种手感好点
![image](https://github.com/user-attachments/assets/35253b71-6d56-47b6-9844-e3c54b51b364)
是30分位15脉冲的，和常规20分位20脉冲与点不一样
