### ISSUE TITLE
睡眠存在问题

### ISSUE THREAD

**Issue by boulevard-h** [genokolar/nrf52-keyboard#30]
使用最新版 Release：SDK17.1 20230303-1178c72e 变异固件时，发现睡眠出现问题。
我的设备使用了蓝牙与USB的状态指示灯，在蓝牙模式下，当长时间不使用键盘进入休眠模式后，蓝牙指示灯熄灭。然后在不到一秒后，蓝牙与USB指示灯同时短暂闪烁一下，然后蓝牙指示灯回复常亮，说明退出了休眠模式。

**Comment by genokolar** [comment]
暂未发现其他人反馈这个问题，请核查其他影响因素

**Comment by boulevard-h** [comment]
> 暂未发现其他人反馈这个问题，请核查其他影响因素

感谢您的回复，的确是我自己的电路设计存在问题，目前已经解决。
