### ISSUE TITLE
这个支持多旋钮吗

### ISSUE THREAD

**Issue by jeromeli002** [genokolar/nrf52-keyboard#6]
格老师 请问这个支持多旋钮吗，有像qmk那样支持多旋钮吗？
如果可以支持要怎么添加？？

**Comment by genokolar** [comment]
暂时不支持。

**Comment by jeromeli002** [comment]
写了支持 52810 52811 52832 ，可是改成52811编译不了， 是直接刷52810的固件吗？还是要怎么修改才能编译出52811固件

**Comment by genokolar** [comment]
不支持。要的话需要自己改代码
