### ISSUE TITLE
Flashing GT-BLE60 Rev D All Fails

### ISSUE THREAD

**Issue by pseudobacon** [genokolar/nrf52-keyboard#9]
![image](https://user-images.githubusercontent.com/12183854/134390010-dea08f71-4527-4690-98c0-7151c0184dd6.png)

There is no option for Rev. E in CMSIS-DAP线刷20210424-稳定版, so I copied the latest all .hex file. 919, 822, 817 all of these files cannot be flashed

**Comment by genokolar** [comment]
the mergehex executable issue：where merging hex files could produce sections with conflicting data, rendering the output hex file invalid.
i will fix the actions
